HOST: http://cv.uoc.edu/

--- GUAITA ---

---
Serveis per la monitorització de les aules i llurs eines
---

--
Professor/Consultor
Serveis de la pàgina d'aules del docent
--

Llista d'assignatures d'un idp
GET /app/guaita/assignatures{?s,perfil}
< 200
< Content-Type: application/json
{}

Llista d'aules d'una assignatura per un any acadèmic
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules{?s,idp}
< 200
< Content-Type: application/json
{}

Detall d'una aula
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules/{codAula}/{domainIdAula}/{domainCode}{?s,idp}
< 200
< Content-Type: application/json
{}

Eines d'una aula
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules/{codAula}/{domainIdAula}/{domainCode}/eines{?s,idp}
< 200
< Content-Type: application/json
{}

Activitats d'una aula
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules/{codAula}/{domainIdAula}/{domainCode}/activitats{?s}
< 200
< Content-Type: application/json
{}

Eines d'una activitat d'una aula
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules/{codAula}/{domainIdAula}/{domainCode}/activitats/{eventId}/eines{?s,idp}
< 200
< Content-Type: application/json
{}

Avaluacio d'una aula
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules/{codAula}/{domainIdAula}/{domainCode}/avaluacio{?s}
< 200
< Content-Type: application/json
{}

Eines d'una aula per consultor
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules/{codAula}/{domainIdAula}/{domainCode}/consultor/{idp}/eines{?s}
< 200
< Content-Type: application/json
{}

Activitats d'una aula per consultor
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules/{codAula}/{domainIdAula}/{domainCode}/consultor/{idp}/activitats{?s}
< 200
< Content-Type: application/json
{}

Eines d'una aula per estudiant
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules/{codAula}/{domainIdAula}/{domainCode}/estudiant/{idp}/eines{?s}
< 200
< Content-Type: application/json
{}

Activitats d'una aula per estudiant
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules/{codAula}/{domainIdAula}/{domainCode}/estudiant/{idp}/activitats{?s}
< 200
< Content-Type: application/json
{}

Eines d'una activitat per estudiant
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules/{codAula}/{domainIdAula}/{domainCode}/estudiant/{idp}/activitats/{eventId}/eines{?s}
< 200
< Content-Type: application/json
{}

--
Estudiant
Serveis de les aules d'un estudiant
--

Widget d'una aula per estudiant
GET /app/guaita/assignatures/{anyAcademic}/{codAssignatura}/{domainId}/aules/{codAula}/{domainIdAula}/{domainCode}/widget{?s}
< 200
< Content-Type: application/json
{}

Plana d'aules de l'estudiant
GET /app/guaita/estudiant{?s}
< 200
< Content-Type: application/json
{}
