# Guaita
## Informe d'errors
### Processar logs

```{r}
library(ggplot2)
library(lubridate)
library(plyr)

setwd("/home/campus/nodejsHome/guaita/log")
system("rm error.csv", intern = TRUE, ignore.stderr = TRUE)
system("rm connections.csv", intern = TRUE, ignore.stderr = TRUE)

log.processa <- function(frontend) {
  system(sprintf("gzip -df %s/guaita.sys.log*", frontend), intern = TRUE, ignore.stderr = TRUE)
  system(sprintf("grep -A 2 -B 2 -hn 'TypeError' %s/guaita.sys* > %s/error.log", frontend, frontend), intern = TRUE, ignore.stderr = TRUE)
  system(sprintf("cat %s/guaita.sys* > %s/connections.log", frontend, frontend), intern = TRUE, ignore.stderr = TRUE)
}

frontends <- c("calonge", "escaro", "planes", "ripoll")
lapply(frontends, log.processa)
system("python logs.py", intern = TRUE, ignore.stderr = TRUE)

```

### Errors

```{r}
error <- read.delim("error.csv", header=F)
names(error) <- c("frontend","date","call", "error", "class")
error$date <- strptime(error$date, format = "%Y/%m/%d %H:%M:%S")
error$hour <- cut(error$date, breaks = "hour")
error <- error[order(error$date),]
error$date <- as.character(error$date)
error$hour <- as.character(error$hour)

error.summary <- ddply(error, .(frontend, hour), summarise, count=length(frontend))

now <- as.POSIXlt(format(Sys.time(), "%Y/%m/%d %H:00:00"))
tseq <- as.character(seq(now - days(2), length.out=48, by="hour"))
error.base <- expand.grid(frontend=frontends, hour=tseq, count=c(0))
error.total <- ddply(merge(error.summary, error.base, all.x=TRUE, all.y=TRUE), .(frontend, hour), summarise, count=sum(count))
ggplot(error.total, aes(x=hour, y=count, fill=frontend)) + geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

### Connections

```{r}
connections <- read.delim("connections.csv", header=F)
names(connections) <- c("frontend","date","call", "session")
connections$date <- strptime(connections$date, format = "%Y/%m/%d %H:%M:%S")
connections$hour <- cut(connections$date, breaks = "hour")
connections$date <- as.character(connections$date)
connections$hour <- as.character(connections$hour)

connections.summary <- ddply(connections, .(frontend, hour), summarise, count=length(unique(session)))

now <- as.POSIXlt(format(Sys.time(), "%Y/%m/%d %H:00:00"))
tseq <- as.character(seq(now - days(2), length.out=48, by="hour"))
connections.base <- expand.grid(frontend=frontends, hour=tseq, count=c(0))
connections.total <- ddply(merge(connections.summary, connections.base, all.x=TRUE, all.y=TRUE), .(frontend, hour), summarise, count=sum(count))
ggplot(connections.total, aes(x=hour, y=count, fill=frontend)) + geom_bar() + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```
